name: Post merge
on:
  push:
    branches: [ master ]

jobs:
  allChecks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Run all checks
      run: ./gradlew check --stacktrace
    
  instrumentationTests:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Run Instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with: 
        aoi-level: 29
        script: ./gradlew connectedCheck --stacktrace
        
  deploy:
    runs-on: ubuntu-latest
    needs: [allChecks, instrumentationTests]
    
    steps:
      - uses: action/checkout@v2
      - name: Build Snapshot
        run: ./gradlew assemble --stacktrace
    
    
